### ISSUE TITLE
Matrix is not visible in some cases

### ISSUE THREAD

**Issue by alanhussey** [cowchimp/source-viz#2]
While trying to reduce the example code for #1, I found that (when I didn't hit the bug in #1) the Adjacency Matrix would render too small to show its contents:

<img width="188" alt="screen shot 2019-02-07 at 8 01 23 am" src="https://user-images.githubusercontent.com/383725/52424318-9987ca00-2aae-11e9-8b03-9710fdb5096d.png">

```js
import a from './a';
import b from './a';

export function myLongMethodA() {
  return a + b;
}
```

<img width="107" alt="screen shot 2019-02-07 at 8 02 51 am" src="https://user-images.githubusercontent.com/383725/52424407-cfc54980-2aae-11e9-9e28-76baaa5b4f06.png">

```js
class A {
  constructor() {
    this._b = [];
  }

  methodC() {
      return this._b;
  }
}
```

**Comment by cowchimp** [comment]
I know it's been a while since you opened this issue, but it should now be resolved.
You can try it at:
https://source-viz.netlify.app
